{{- $extraPipPackages := .Values.airflow.extraPipPackages }}
{{- $volumeMounts := include "airflow.volumeMounts" (dict "Release" .Release "Values" .Values "extraPipPackages" $extraPipPackages) }}
{{- $volumes := include "airflow.volumes" (dict "Release" .Release "Values" .Values "extraPipPackages" $extraPipPackages) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "airflow.fullname" . | trunc 19 }}-db-{{ (print .Values) | sha1sum }}
  labels:
    app: airflow
    component: jobs
    chart: airflow-8.4.1
    release: RELEASE-NAME
    heritage: Helm
spec:
  template:
    metadata:
      annotations:
      labels:
        app: airflow
        component: jobs
        chart: airflow-8.4.1
        release: RELEASE-NAME
        heritage: Helm
    spec:
      restartPolicy: OnFailure
      serviceAccountName: RELEASE-NAME
      initContainers:        
        - name: check-db  
          image: apache/airflow:2.1.1-python3.8
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 50000
            runAsGroup: 50000
          envFrom:    
            - secretRef:
                name: "RELEASE-NAME-config"
          env:    
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: RELEASE-NAME-postgresql
                  key: postgresql-password
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: RELEASE-NAME-redis
                  key: redis-password
          command:
            - "/usr/bin/dumb-init"
            - "--"
          args:
            - "bash"
            - "-c"
            - "exec timeout 60s airflow db check"
      containers:
        - name: upgrade-db          
          image: apache/airflow:2.1.1-python3.8
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 50000
            runAsGroup: 50000
          envFrom:            
            - secretRef:
                name: "RELEASE-NAME-config"
          env:            
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: RELEASE-NAME-postgresql
                  key: postgresql-password
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: RELEASE-NAME-redis
                  key: redis-password
          command:
            - "/usr/bin/dumb-init"
            - "--"
          args:
            - "bash"
            - "-c"
            - "exec airflow db upgrade"
